(function() {
  var data;

  data = [
    {
      name: "Monster",
      count: 1
    }, {
      name: "Rails",
      count: 2
    }, {
      name: "Test",
      count: 1
    }
  ];

  this.basic = function() {
    var table, tbody, tr;
    table = d3.select("body").append("table");
    tbody = table.append("tbody");
    tr = tbody.selectAll("tr").data(data).enter().append("tr");
    tr.append("td").text(function(d) {
      return d.name;
    });
    return tr.append("td").text(function(d) {
      return d.count;
    });
  };

}).call(this);

// Generated by CoffeeScript 1.5.0-pre
