(function() {

  this.treemap = function() {
    var color, d_data, div, height, node, treemap, width;
    width = 200;
    height = 200;
    d_data = {
      name: "skills",
      children: [
        {
          name: "Ruby",
          skill_level: 70
        }, {
          name: "Javascript",
          skill_level: 90
        }, {
          name: "R",
          skill_level: 20
        }, {
          name: "Objective-C",
          skill_level: 60
        }, {
          name: "Python",
          skill_level: 60
        }
      ]
    };
    div = d3.select("body").append("div").attr("id", "treemap");
    color = d3.scale.category20c();
    treemap = d3.layout.treemap().size([width, height]).sticky(true).padding(10).value(function(d) {
      return d.skill_level;
    });
    return node = div.datum(d_data).selectAll(".node").data(treemap.nodes).enter().append("div").attr("class", "node").style("background", function(d) {
      if (d.children) {
        return null;
      } else {
        return color(d.name);
      }
    }).style("left", function(d) {
      return d.x + "px";
    }).style("top", function(d) {
      return d.y + "px";
    }).style("width", function(d) {
      return Math.max(0, d.dx - 1) + "px";
    }).style("height", function(d) {
      return Math.max(0, d.dy - 1) + "px";
    }).text(function(d) {
      if (d.children) {
        return null;
      } else {
        return d.name;
      }
    });
  };

}).call(this);

// Generated by CoffeeScript 1.5.0-pre
